source 'http://rubygems.org'

group :server do
  gem 'sinatra'
  gem 'haml'
end

group :test do
  gem 'test-unit', '~> 2.5.5'
  gem 'shoulda-context', '~> 1.1.4'
  gem 'rr', '~> 1.1.1'
  gem 'test-unit-rr'
end