# -*- coding: utf-8 -*-
task :default => :test
desc "テストを実行する"
task :test do
  sh "/usr/bin/env ruby test/run-test.rb --priority-mode --default-priority=must"
end

desc "pryを起動する"
task :console do
  sh "pry -I./lib -r solver"
end
task :irb => :console

desc "serverを起動"
task :server do
  sh "/usr/bin/env ruby lib/server.rb"
end
